---
- name: Define Homebrew directory
  set_fact:
    homebrew_dir: "{{ lookup('env','HOME') }}/opt/homebrew"

- name: Define Homebrew environment
  set_fact:
    homebrew_env:
      PATH: "{{ ansible_env.PATH }}:{{ homebrew_dir }}/bin"

- name: Prepare Homebrew directory
  file: path="{{ homebrew_dir }}" state=directory mode=0750

- name: Install Homebrew
  shell: curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C "{{ homebrew_dir }}"
  args:
    creates: "{{ homebrew_dir }}/bin/brew"
    warn: no

- name: Tap the Homebrew Cask repository.
  homebrew_tap: tap=caskroom/cask state=present
  environment: "{{ homebrew_env }}"
