---
# Ensure that we have proper environment management before doing anything else.
- include: homebrew.yml
  when: ansible_os_family == "Darwin"
- include: go.yml
- include: python.yml

- include: git.yml
- include: ipython.yml
- include: slate.yml
  when: ansible_os_family == "Darwin"
- include: terminfo.yml
- include: zsh.yml
- include: vim.yml
