---
# Ensure that we have proper environment management before doing anything else.
- import_tasks: homebrew.yml
  when: ansible_os_family == "Darwin"
- import_tasks: go.yml
- import_tasks: python.yml

- import_tasks: git.yml
- import_tasks: ipython.yml
- import_tasks: keyboard.yml
- import_tasks: osx_defaults.yml
  when: ansible_os_family == "Darwin"
- import_tasks: osx_apps.yml
  when: ansible_os_family == "Darwin"
- import_tasks: terminfo.yml
- import_tasks: zsh.yml
- import_tasks: vim.yml
