---
- name: Install Slate
  community.general.homebrew_cask: name=slate
  environment: "{{ homebrew_env }}"

- name: Copy Slate config
  copy: src=slate.js dest=~/.slate.js

- name: Install Chrome
  community.general.homebrew_cask:
    name: google-chrome
    state: installed
  environment: "{{ homebrew_env }}"

- name: Add Chrome to dock
  shell: dockutil --add '/Applications/Google Chrome.app' --replacing 'Google Chrome'
  environment: "{{ homebrew_env }}"

- name: Install Drive
  community.general.homebrew_cask:
    name: google-drive-file-stream
    state: installed
  environment: "{{ homebrew_env }}"

- name: Install VSCode
  community.general.homebrew_cask:
    name: visual-studio-code
    state: installed
  environment: "{{ homebrew_env }}"

- name: Add VSCode to dock
  shell: dockutil --add '/Applications/Visual Studio Code.app' --replacing 'Visual Studio Code'
  environment: "{{ homebrew_env }}"

- name: Install Whatsapp
  community.general.homebrew_cask:
    name: whatsapp
    state: installed
  environment: "{{ homebrew_env }}"

- name: Add Whatsapp to dock
  shell: dockutil --add '/Applications/Whatsapp.app' --replacing 'Whatsapp'
  environment: "{{ homebrew_env }}"

- name: Install Spotify
  community.general.homebrew_cask:
    name: spotify
    state: installed
  environment: "{{ homebrew_env }}"

- name: Add Spotify to dock
  shell: dockutil --add '/Applications/Spotify.app' --replacing 'Spotify'
  environment: "{{ homebrew_env }}"
