---
- name: Define Python directory
  set_fact:
    python_dir: "{{ lookup('env','HOME') }}/Library/Python/3.7"

- name: Define Python environemnt
  set_fact:
    python_env:
      PATH: "{{ ansible_env.PATH }}:{{ python_dir }}/bin"
