---
- name: Prepare autoload directory
  file: path=~/.vim/autoload state=directory mode=0750

- name: Install pathogen
  copy: src=pathogen.vim dest=~/.vim/autoload mode='0640'

- name: Prepare bundle directory
  file: path=~/.vim/bundle state=directory mode=0750

- name: Copy the vimrc
  copy: src=vimrc dest=~/.vimrc mode='0640'

- name: Install vim-autoclose
  git: repo=https://github.com/Townk/vim-autoclose.git
       dest=~/.vim/bundle/vim-autoclose

- name: Install vimagit
  git: repo=https://github.com/jreybert/vimagit.git
       dest=~/.vim/bundle/vimagit

- name: Install ctags through brew (required for tagbar)
  homebrew: name=ctags
  environment: "{{ homebrew_env }}"
  when: ansible_os_family == "Darwin"

- name: Install ctags through apt (required for tagbar)
  apt: name=exuberant-ctags
  when: ansible_os_family == "Debian"
  become: yes
